#!/usr/bin/env bash
# .github/workflows/build_toc.sh — regenerate a SPEC's Table of contents.
#
# Usage:
#   build_toc.sh                       # rewrite the SPEC TOC in place
#   build_toc.sh --check               # exit-code taxonomy below; no rewrite
#   build_toc.sh --migrate             # convert a legacy anchor-link ToC to markers
#   build_toc.sh --spec <path> [...]   # operate on <path> instead of the default SPEC
#
# --check exit codes:
#   0 clean · 1 stale (markers present, body differs) · 2 hard error (no numbered
#   headings / SPEC not found / bad arg) · 3 marker-less (legacy anchor-link ToC —
#   run --migrate) · 4 corrupt markers (START present, END missing — repair them).
#
# --migrate converts a marker-less anchor-link ToC to the line-number marker form:
# gated on marker absence (a no-op on a SPEC that already has markers), guarded
# (refuses byte-unchanged when the SPEC has no numbered `## N.` heading), and
# content-preserving (replaces only the contiguous ToC-list lines, keeping prose).
#
# Default SPEC is a SPEC.md self-located relative to this script's dir, so
# existing callers (`build_toc.sh`, `build_toc.sh --check`) are unchanged.
# `--spec <path>` (or `--spec=<path>`) points the same logic at another SPEC —
# this is how the shipped `check-toc.yml` validates this repo's SPEC ToC.
# Arguments may appear in any order.
#
# The TOC lives between the markers:
#   <!-- TOC START — generated by .github/workflows/build_toc.sh; do not edit by hand -->
#   <!-- TOC END -->
#
# It enumerates every heading at depth 2-4 whose first token is a section
# number (e.g. `## 0. Intent and scope`, `### 1.4 PR-as-living-doc`,
# `#### 5.7.1 Operating modes …`). Each row shows the section id, the
# title, and the line number — enabling targeted Read --offset --limit.

set -uo pipefail

SHELL_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd -P)"
SPEC="$SHELL_ROOT/SPEC.md"   # default: the self-located SPEC (unchanged)
MODE="write"

while [ $# -gt 0 ]; do
  case "$1" in
    --check)    MODE="--check" ;;
    --migrate)  MODE="--migrate" ;;
    write)      MODE="write" ;;
    --spec)     shift; SPEC="${1:?build_toc: --spec requires a path}" ;;
    --spec=*)   SPEC="${1#--spec=}" ;;
    *) echo "build_toc: unknown argument: $1" >&2; exit 2 ;;
  esac
  shift
done

if [ ! -f "$SPEC" ]; then
  echo "build_toc: SPEC not found at $SPEC" >&2
  exit 2
fi

TOC_START='<!-- TOC START — generated by .github/workflows/build_toc.sh; do not edit by hand -->'
TOC_END='<!-- TOC END -->'

# awk program — single source of truth for heading→TOC-row formatting.
# Filters depth-2/3/4 headings whose first token matches a section-number
# pattern (digits with optional dots), emits a markdown table row with
# &nbsp; indentation, the § sigil, the title, and the line number.
AWK_PROG='
  /^#{2,4} [0-9]/ {
    n = 0
    while (substr($0, n + 1, 1) == "#") n++
    rest = substr($0, n + 2)
    sp = index(rest, " ")
    if (sp == 0) next
    id = substr(rest, 1, sp - 1)
    title = substr(rest, sp + 1)
    sub(/\.$/, "", id)
    if (id !~ /^[0-9]+(\.[0-9]+)*$/) next
    indent = ""
    for (i = 0; i < n - 2; i++) indent = indent "&nbsp;&nbsp;"
    printf("| %s\xc2\xa7%s | %s | %d |\n", indent, id, title, NR)
  }
'

# render_toc_into <output_path>
#   Reads $SPEC, builds the TOC block, writes the full SPEC contents with
#   the new TOC spliced in, to <output_path>.
render_toc_into() {
  local out="$1"
  local start_ln end_ln new_body new_block
  start_ln=$(grep -nF "$TOC_START" "$SPEC" | head -1 | cut -d: -f1)
  if [ -z "$start_ln" ]; then
    echo "build_toc: no TOC markers in $SPEC — legacy/anchor-link ToC. build_toc.sh --migrate converts it ONLY when $SPEC already uses numbered '## N.' headings and a '## Table of contents' block; otherwise number the headings ('## N. Title') or add the <!-- TOC START -->/<!-- TOC END --> markers by hand." >&2
    return 3
  fi
  # Pin end_ln to the first END marker STRICTLY AFTER start_ln so prose
  # mentions of the markers don't false-match.
  end_ln=$(awk -v start="$start_ln" -v needle="$TOC_END" '
    NR > start && index($0, needle) { print NR; exit }
  ' "$SPEC")
  if [ -z "$end_ln" ]; then
    echo "build_toc: corrupt TOC markers in $SPEC (START without END) — repair the markers" >&2
    return 4
  fi

  new_body=$(awk "$AWK_PROG" "$SPEC")
  if [ -z "$new_body" ]; then
    echo "build_toc: no numbered headings found in SPEC.md" >&2
    return 2
  fi
  new_block="$TOC_START
| Section | Title | Line |
|---|---|---|
$new_body
$TOC_END"

  {
    head -n $((start_ln - 1)) "$SPEC"
    printf '%s\n' "$new_block"
    tail -n +$((end_ln + 1)) "$SPEC"
  } > "$out"
}

# --migrate mode: convert a marker-less (legacy anchor-link) ToC to the
# line-number marker form. gate → guard → transactional splice → fill →
# atomic replace. Never leaves a partial/empty-marker state on the live SPEC.
if [ "$MODE" = "--migrate" ]; then
  if grep -qF "$TOC_START" "$SPEC"; then
    # Markers already present — idempotent no-op via the normal write path.
    MODE="write"
  else
    # Guard-before-mutate: require at least one numbered `## N.`-style heading,
    # else refuse and leave the SPEC byte-unchanged (never destroy content).
    if ! grep -qE '^#{2,4} [0-9]' "$SPEC"; then
      echo "build_toc: no numbered '## N.' headings in $SPEC — number your section headings as '## N. Title' first, then re-run build_toc.sh --migrate" >&2
      exit 5
    fi
    # Transactional splice into a TEMP copy — the live SPEC is untouched until
    # the final atomic mv.
    #
    # This and the three sibling mktemp calls below are the shell's fourth
    # ambient-rooted write location, scored against SPEC §5.5's state
    # boundary with the others (issue #127). A bare mktemp is rooted at the
    # ambient temporary root by definition, so it can land inside a
    # repository the shell does not govern. Enumerated rather than closed,
    # on the secret-scan spool's own ground: every path here unlinks or
    # moves its temporary within the same run, so nothing persists to become
    # another repository's committable content — unlike the dispatch
    # scratch, which persisted and was therefore closed rather than
    # enumerated. The ground is scoped to this script's own EXIT PATHS: an
    # INTERRUPTED run leaves its temporary behind, since only the --check
    # mode installs an EXIT trap. That is the same orphan shape
    # provision.ts names as its own residual for an uncleanly killed
    # dispatcher, and it is named here rather than claimed away.
    mig=$(mktemp)
    if grep -qE '^## Table of contents[[:space:]]*$' "$SPEC"; then
      # Replace the legacy ToC-list block under the existing heading. The STANDARD
      # markdown layout puts a blank line between the heading and its list, so we
      # first SKIP any leading blank lines, THEN delete the contiguous list/table/
      # anchor block (list item `- `/`* `/`1. `, table row `| … |`, or a `[…](#…)`
      # anchor), stopping at the first blank line or `---` that FOLLOWS the list.
      # The empty marker block is inserted after the heading (one blank line, then
      # markers); the trailing blank/`---` framing and all real prose survive.
      awk -v S="$TOC_START" -v E="$TOC_END" '
        !done && /^## Table of contents[[:space:]]*$/ {
          print; print ""; print S; print E; done=1; phase="leadblank"; next
        }
        phase=="leadblank" {
          if ($0 ~ /^[[:space:]]*$/) next   # skip blank(s) between heading and list
          phase="list"                       # first non-blank enters list-delete
        }
        phase=="list" {
          if ($0 ~ /^[[:space:]]*[-*+] / || $0 ~ /^[[:space:]]*[0-9]+\. / || $0 ~ /^[[:space:]]*\|/ || $0 ~ /\]\(#/) next
          phase=""                           # blank/`---`/prose ends the list block
        }
        { print }
      ' "$SPEC" > "$mig"
    else
      # No ToC heading — insert one plus the empty marker block immediately
      # before the first `## ` heading.
      awk -v S="$TOC_START" -v E="$TOC_END" '
        !done && /^## / {
          print "## Table of contents"; print ""; print S; print E; print ""
          done=1
        }
        { print }
      ' "$SPEC" > "$mig"
    fi
    # Assert the splice inserted a resolvable empty marker block; else refuse
    # with the live SPEC byte-unchanged (we only ever wrote to the temp copy).
    if ! grep -qF "$TOC_START" "$mig" || ! grep -qF "$TOC_END" "$mig"; then
      echo "build_toc: --migrate found no place to insert TOC markers in $SPEC — left unchanged" >&2
      rm -f "$mig"; exit 2
    fi
    # Fill the empty markers by write-convergence on the temp copy.
    SPEC_ORIG="$SPEC"; SPEC="$mig"
    for pass in 1 2 3; do
      tmp=$(mktemp)
      render_toc_into "$tmp" || { rc=$?; rm -f "$tmp" "$mig"; exit $rc; }
      if cmp -s "$SPEC" "$tmp"; then rm -f "$tmp"; break; fi
      mv "$tmp" "$SPEC"
    done
    # Assert a non-empty ToC body before the atomic replace.
    if ! grep -qF "$TOC_START" "$mig" || ! grep -qF "$TOC_END" "$mig" || ! grep -qF '§' "$mig"; then
      echo "build_toc: --migrate produced no ToC body for $SPEC_ORIG — left unchanged" >&2
      rm -f "$mig"; exit 2
    fi
    mv "$mig" "$SPEC_ORIG"
    echo "build_toc: migrated $SPEC_ORIG to line-number TOC markers."
    exit 0
  fi
fi

# --check mode: render to a temp file, compare, never write to SPEC.
if [ "$MODE" = "--check" ]; then
  tmp=$(mktemp)
  trap 'rm -f "$tmp"' EXIT
  render_toc_into "$tmp" || exit $?
  if cmp -s "$SPEC" "$tmp"; then
    exit 0
  fi
  echo "build_toc: SPEC.md TOC is out of sync." >&2
  echo "build_toc: run .github/workflows/build_toc.sh to regenerate." >&2
  exit 1
fi

# write mode: iterate to fixed point. The first pass uses line numbers
# from the *input* file; replacing the TOC block shifts every numbered
# heading by the size delta. The second pass reads the new file and
# emits correct line numbers. Heading count is invariant across passes,
# so the TOC SIZE is stable from pass 2 onward — fixed-point in ≤2
# iterations. The bound `2` here is a safety cap, not an optimization.
for pass in 1 2 3; do
  tmp=$(mktemp)
  render_toc_into "$tmp" || { rc=$?; rm -f "$tmp"; exit "$rc"; }
  if cmp -s "$SPEC" "$tmp"; then
    rm -f "$tmp"
    echo "build_toc: SPEC.md TOC up to date (converged in pass $pass)."
    exit 0
  fi
  mv "$tmp" "$SPEC"
done

# If we reach here, the TOC didn't converge in 3 passes — should be impossible
# given heading-count invariance. Surface it loudly rather than loop forever.
echo "build_toc: TOC failed to converge after 3 passes — check for marker corruption" >&2
exit 2
